media/authentication/urls.py
from django.urls import path
from .views import MySignupView, MyLoginView, LogoutView

app_name = 'authentication'

urlpatterns = [
    path('signup/', MySignupView.as_view(), name='signup'),
    path('login/', MyLoginView.as_view(), name='login'),
    # path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

media/core/urls.py
from django.urls import path
from .views import ProfileView, PfpView, ContactView, ContactSuccessView

app_name = 'core'

urlpatterns = [
    path('profile/<int:userid>/', ProfileView.as_view(), name='profile'),
    path('profile/pfile/<pfpname>', PfpView.as_view(), name='pfp'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/success/', ContactSuccessView.as_view(), name='success'),
]

media/media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView
from authentication.views import MyLoginView, MySignupView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mediaApp/')),
    path('mediaApp/', include('mediaApp.urls')),  
    path('core/', include('core.urls')),
    path('auth/', include('authentication.urls')),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', MySignupView.as_view(), name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

media/mediaApp/urls.py
from django.urls import path
from .views import Index, Upload, Viewer, FileViewer, ThumbViewer, DeleteVideoView, EditVideoInfoView, ThumbnailGeneratorView

app_name = 'mediaApp'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('upload/', Upload.as_view(), name='upload'),
    path('watch/<int:video_id>/', Viewer.as_view(), name='watch'),
    path('file/<str:file_name>/', FileViewer.as_view(), name='file'),
    path('thumb/<str:file_name>/', ThumbViewer.as_view(), name='thumb'),
    path('delete/<int:video_id>/', DeleteVideoView.as_view(), name='delete'),
    path('edit/<int:video_id>/', EditVideoInfoView.as_view(), name='edit'),
    path('generate_thumbnail/<int:video_id>/', ThumbnailGeneratorView.as_view(), name='generate_thumbnail'),
]

media/mediaApp/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User

EXTENSIONS = ['mp4', 'avi', 'wav', 'mov', 'webm']


class Tag(models.Model):
    name = models.CharField(max_length=255)


class Video(models.Model):
    title = models.CharField(max_length=255)
    original_image = models.ImageField(upload_to='original_images/')
    description = models.CharField(max_length=1024)
    views = models.PositiveIntegerField(default=0)
    file = models.FileField(validators=[FileExtensionValidator(allowed_extensions=EXTENSIONS)])
    upload_date = models.DateTimeField(default=now)
    numberOfViews = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        ordering = ['upload_date']

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    text = models.CharField(max_length=255)
    post_date = models.DateTimeField(default=now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

    class Meta:
        ordering = ['post_date']

    def __str__(self) -> str:
        return self.text


class VideoTag(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

media/mediaApp/forms.py
from django import forms

class MediaUploadForm(forms.Form):
    title = forms.CharField(max_length=255, label='Title')
    description = forms.CharField(max_length=1024)
    video = forms.FileField(label='Select a video to upload')
    tag = forms.CharField(max_length=255, label='Point tags')


class SearchMediaForm(forms.Form):
    query = forms.CharField(label='Search')

class CommentForm(forms.Form):
    comment_text = forms.CharField(max_length=255, label='Comment')

media/mediaApp/views.py
from wsgiref.util import FileWrapper
from django.http import StreamingHttpResponse
from django.core.exceptions import ValidationError
from django.views.generic.list import ListView
from django.db.models import Q
from django.views import View
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import Video, VideoTag, Tag, Comment
from .forms import MediaUploadForm, SearchMediaForm, CommentForm
from media import settings
from PIL import Image
import mimetypes
import re
import os
import ffmpeg
import sys


class Index(ListView):
    template_name = 'mediaApp/index.html'
    form_class = SearchMediaForm
    paginate_by = 3
    context_object_name = 'data'
    model = Video

    def get_queryset(self):
        query = self.request.GET.get('q')
        tag = self.request.GET.get('tag')
        if query:
            # annotate(rank=SearchRank(SearchVector('views'), SearchQuery(query))).order_by('-rank')
            return Video.objects.filter(Q(title__icontains=query))
        elif tag:
            video_tags = VideoTag.objects.filter(Q(tag__name__iexact=tag))
            return list([tag.video for tag in video_tags])
        else:
            return self.model.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', None)
        context['tag'] = self.request.GET.get('tag', None)
        context['videoqnt'] = Video.objects.all().count()
        return context


class ThumbnailGeneratorView(View):
    def get(self, request, video_id):
        video = get_object_or_404(Video, pk=video_id)

        # Open the original image using Pillow
        original_image = Image.open(video.original_image.path)

        # Generate a thumbnail (replace dimensions with your desired size)
        thumbnail = original_image.resize((100, 100))

        # Serve the thumbnail
        response = HttpResponse(content_type="image/jpeg")
        thumbnail.save(response, "JPEG")
        return response

class Upload(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'mediaApp/upload.html',
                      context={'form': MediaUploadForm, 'user': request.user}
                      )

    def post(self, request, *args, **kwargs):
        form = MediaUploadForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                video_file = request.FILES['video']
            except ValidationError:
                return redirect('/mediaApp/upload')
            else:
                title = request.POST['title']
                description = request.POST['description']
                tags_arr = request.POST['tags'].split()
                tags = []
                for s in tags_arr:
                    t = Tag()
                    t.name = s
                    t.save()
                    tags.append(t)

                video_model = Video()
                video_model.title = title
                video_model.file = video_file
                video_model.description = description
                video_model.author = request.user
                video_model.save()
                for t in tags:
                    video_tag = VideoTag()
                    video_tag.tag = t
                    video_tag.video = video_model
                    video_tag.save()
                generate_thumbnail(video_file, video_model)
        return redirect('/mediaApp/')


class Viewer(View):

    def get(self, request, video_id):
        video = Video.objects.get(id=video_id)
        video.views += 1
        video.save()
        video_tags = VideoTag.objects.filter(video=video)
        tags = set([video.tag for video in video_tags])
        comments = Comment.objects.filter(video=video)
        form = CommentForm
        context = {'video': video, 'tags': tags, 'form': form, 'comments': comments}
        return render(request, 'mediaApp/view.html', context=context)

    def post(self, request, video_id):
        form = CommentForm(request.POST)
        if form.is_valid():
            content = request.POST['comment']
            comment = Comment()
            comment.text = content
            comment.author = request.user
            video = Video.objects.get(id=video_id)
            comment.video = video
            comment.save()
        return redirect(f'/mediaApp/watch/{video_id}')


class FileViewer(View):

    def file_iterator(self, file_name, chunk_size=8192, offset=0, length=None):
        with open(settings.MEDIA_ROOT + file_name, "rb") as f:
            f.seek(offset, os.SEEK_SET)
            remaining = length
            while True:
                bytes_length = chunk_size if remaining is None else min(remaining, chunk_size)
                data = f.read(bytes_length)
                if not data:
                    break
                if remaining:
                    remaining -= len(data)
                yield data

    def get(self, request, file_name):
        path = file_name
        range_header = request.META.get('HTTP_RANGE', '').strip()
        range_re = re.compile(r'bytes\s*=\s*(\d+)\s*-\s*(\d*)', re.I)
        range_match = range_re.match(range_header)
        size = os.path.getsize(settings.MEDIA_ROOT + path)
        content_type, encoding = mimetypes.guess_type(path)
        content_type = content_type or 'application/octet-stream'
        if range_match:
            first_byte, last_byte = range_match.groups()
            first_byte = int(first_byte) if first_byte else 0
            last_byte = first_byte + 1024 * 1024 * 8  # 8M per piece, the maximum volume of the response body
            if last_byte >= size:
                last_byte = size - 1
            length = last_byte - first_byte + 1
            resp = StreamingHttpResponse(self.file_iterator(path, offset=first_byte, length=length), status=206,
                                         content_type=content_type)
            resp['Content-Length'] = str(length)
            resp['Content-Range'] = 'bytes %s-%s/%s' % (first_byte, last_byte, size)

        else:
            # When the video stream is not obtained, the entire file is returned in the generator mode to save memory.
            resp = StreamingHttpResponse(FileWrapper(open(path, 'rb')), content_type=content_type)
            resp['Content-Length'] = str(size)
        resp['Accept-Ranges'] = 'bytes'
        return resp


class ThumbViewer(View):

    def get(self, request, file_name):
        file = file_name.replace('.mp4', '.png')
        with open(settings.MEDIA_ROOT + file, 'rb') as thumb:
            return HttpResponse(content=thumb, content_type='image/png')


def generate_thumbnail(in_filename, video_model):
    file_name = Video.objects.get(id=video_model.id).file.name
    path = settings.MEDIA_ROOT + 'thumb' + file_name.replace('.mp4', '.png').replace(' ', '_')
    try:
        (
            ffmpeg.input(settings.MEDIA_ROOT + in_filename.name, ss='00:00:05')
                  .output(path, vframes=1)
                  .overwrite_output()
                  .run(capture_stdout=True, capture_stderr=True)
        )
    except ffmpeg.Error as error:
        print(error.stderr.decode(), file=sys.stderr)
        sys.exit(1)


class DeleteVideoView(View):

    def post(self, request, video_id):
        video = Video.objects.get(id=video_id)
        if video.author == request.user:
            name = video.file.name
            video.delete()
            os.remove(settings.MEDIA_ROOT + name)
            os.remove(settings.MEDIA_ROOT + 'thumb' + name.replace('.mp4', '.png'))
            return redirect(f'/core/profile/{video.author.id}')
        return redirect('')
    
    def get(self, request, video_id):
        return redirect('')
    
    
class EditVideoInfoView(View):
    
    def post(self, request, video_id):
        video = Video.objects.get(id=video_id)
        if video.author == request.user:
            video.description = request.POST.get('description')
            video.title = request.POST.get('title')
            video.save()
            return redirect(f'/core/profile/{video.author.id}')
        return redirect('')

    def get(self, request, video_id):
        return redirect('')

media/templates/mediaApp/index.html
{% extends '../components/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mediaApp/index.css' %}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-light bg-light">

        <div class="navbar-brand">
            <a href="/mediaApp/">
                <h2>Dream Forge Production</h2>
            </a>
        </div>
        <span class="navbar-text">
            {% if user.is_authenticated %}
                Hello, <a href="/core/profile/{{ user.id }}">{{ user }}</a> - <a href="{% url 'authentication:logout' %}">logout</a>
            {% else %}
                <a href="{% url 'authentication:login' %}">Login</a>
                <a href="{% url 'authentication:signup' %}">Sign Up</a>
            {% endif %}
        </span>

        <span class="navbar-text">
            {% if tag %}
                <a href="/mediaApp/?tag={{ tag }}">#{{ tag }}</a>
            {% endif %}
        </span>
        <span class="navbar-text">
            {{ videoqnt }} videos - <a href="{% url 'mediaApp:upload' %}">Upload video</a>
        </span>

        <form class="form-inline my-2 my-lg-0" action="{% url 'mediaApp:index' %}">
            <input class="form-control mr-sm-2" type="search" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>

    <div class="mt-4">
        <div class="container">
            <div class="row infinite-container">
                {% for video in page_obj %}
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 infinite-item">
                    <!-- Updated: Make the video thumbnail clickable -->
                    <a href="{% url 'mediaApp:watch' video_id=video.id %}">
                        <div class="video-testimonial-block">
                            <div class="video-thumbnail">
                                <img src="{% url 'mediaApp:generate_thumbnail' video_id=video.id %}" alt="" class="img-fluid">
                            </div>
                        </div>
                    </a>
                    <div class="video-testimonial-content">
                        <h4 class="mb10">{{ video.title }}</h4>
                        <small class="form-text text-muted">{{ video.views }} views</small>
                        <p>
                            <img src="/core/profile/{{ video.author.profile.pfp }}" alt="" class="pfp">
                            <a href="/core/profile/{{ video.author.id }}">{{ video.author }}</a>
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                {% if page_obj.has_next %}
                <a class="infinite-more-link" href="?{% if query %}q={{ query }}{% elif tag %}tag={{ tag }}{% endif %}&page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

media/templates/mediaApp/upload.html
{% extends 'components/base.html' %}

{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mediaApp/upload.css' %}">
{% endblock %}


{% block content %}
    <nav class="navbar">
        <div class="navbar-brand">
            <a href="/mediaApp/">
                <h2>Media App</h2>
            </a>
        </div>
    </nav>

    {% if user.is_authenticated %}
        <div class="text-center">
            <form enctype="multipart/form-data" method="post" action="" class="form-signup">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Upload</h1>

                <!-- File form -->
                {{ form.video.errors }}
                <label for="{{ form.video.id_for_label }}" class="sr-only"></label>
                <input class="form-control" id="{{ form.video.id_for_label }}"
                    maxlength="255" name="{{ form.video.html_name }}" type="file" accept="video/mp4,video/x-m4v,video/*" />
                <small class="form-text text-muted">{{ form.video.help_text|safe }}</small>

                <!-- Title form -->
                {{ form.title.errors }}
                <label for="{{ form.title.id_for_label }}" class="sr-only"></label>
                <input class="form-control" id="{{ form.title.id_for_label }}"
                    maxlength="255" name="{{ form.title.html_name }}" placeholder="Title" type="text" />
                <small class="form-text text-muted">{{ form.title.help_text|safe }}</small>

                <!-- Tags form -->
                {{ form.tags.errors }}
                <label for="{{ form.tags.id_for_label }}" class="sr-only"></label>
                <input class="form-control" id="{{ form.tags.id_for_label }}"
                    maxlength="255" name="{{ form.tags.html_name }}" placeholder="Tags" type="text" />
                <small class="form-text text-muted">{{ form.tags.help_text|safe }}</small>

                <!-- Description form -->
                {{ form.description.errors }}
                <label for="{{ form.description.id_for_label }}" class="sr-only"></label>
                <input class="form-control" id="{{ form.description.id_for_label }}"
                    maxlength="1024" name="{{ form.description.html_name }}" placeholder="Description" type="text" />
                <small class="form-text text-muted">{{ form.description.help_text|safe }}</small>

                <button type="submit" class="btn btn-lg btn-primary btn-block">Upload</button>
            </form>
        </div>
    {% else %}
        <div class="form-text">
            <p>
                You are not logged in. Please log in or sign up if you don't have an account yet.
            </p>
            <br>
            <a href="{% url 'login' %}">Login</a>
            <span> or </span>
            <a href="{% url 'signup' %}">Sign Up</a>
        </div>
    {% endif %}
{% endblock %}
</body>

media/templates/mediaApp/view.html
{% extends 'components/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mediaApp/view.css' %}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-light bg-light">
        <div class="navbar-brand">
            <a href="/mediaApp/">
                <h2>media App</h2>
            </a>
        </div>
        <span class="navbar-text">
            {% if user.is_authenticated %}
                Hello, <a href="/core/profile/{{ user.id }}">{{ user }}</a> - <a href="{% url 'logout' %}">logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'signup' %}">Sign Up</a>
            {% endif %}
        </span>
        <form class="form-inline my-2 my-lg-0" action="{% url 'mediaApp:index' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>

    <div class="container-md my-4">
        <video width="640" height="400" controls>
            <source src="/mediaApp/file/{{ video.file.name }}">
        </video>

        <p>{{ video.title }}</p>
        <p>{{ video.views }}</p>
        <p>{{ video.description }}</p>
        
        {% for tag in tags %}
            <a target="_blank" href="/mediaApp/?tag={{ tag.name }}">#{{ tag.name }}</a>
        {% endfor %}
        <br>

        {% if user.is_authenticated %}
            {{ form.comment.errors }}
            <form action="" method="post" class="form-signup"> {% csrf_token %}
                <label for="{{ form.comment.id_for_label }}">Comment</label>
                <input name="{{ form.comment.html_name }}" id="{{ form.comment.id_for_label }}" type="text" placeholder="Add a comment">
                <button type="submit" class="btn btn-lg btn-primary">Submit</button>
            </form>
        {% endif %}

        <div class="container-md my-4">
            {% for comment in comments %}
                <div class="container">
                    <p>{{ comment.text }}</p>
                    <small>{{ comment.author }}</small>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
</body>

media/templates/mediaApp/watch.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mediaApp/watch.css' %}">
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                <video width="100%" controls>
                    <source src="/mediaApp/video/{{ video.id }}/" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
                <h2 class="mt-3">{{ video.title }}</h2>
                <p class="text-muted">{{ video.views }} views</p>
                <p>{{ video.description }}</p>
                <div class="mb-4">
                    {% for tag in tags %}
                        <span class="badge badge-info">#{{ tag.name }}</span>
                    {% endfor %}
                </div>
                <form method="post" action="{% url 'add_comment' video.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Add Comment</button>
                </form>
                <h3 class="mt-4">Comments</h3>
                {% for comment in comments %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <p class="card-text">{{ comment.text }}</p>
                            <p class="card-subtitle text-muted">
                                by <a href="/core/profile/{{ comment.author.id }}">{{ comment.author }}</a>
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <h4>Related Videos</h4>
                <div class="list-group">
                    {% for related_video in related_videos %}
                        <a href="{% url 'mediaApp/watch' video_id=related_video.id %}" class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ related_video.title }}</h5>
                                <small>{{ related_video.views }} views</small>
                            </div>
                            <img src="{% url 'generate_thumbnail' video_id=related_video.id %}" alt="{{ related_video.title }}" class="img-fluid">
                        </a>
                    {% endfor %}
                </div>
                
            </div>
        </div>
    </div>
{% endblock %}
</body>